language: java
jdk:
- oraclejdk8

script:
- ./gradlew build --stacktrace
after_success:
  - gradle/deploy_snapshot.sh
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - $HOME/.gradle
env:
  global:
    - secure: "F82w/aRKU3QmyH4AEZrSY7r5l76w3BNUTTb9x5yYrRRfKBFRL5WpOio7uK4k0jQXEMp4QL/IdAwfYVzHEc+AZTdwr1VReQE18bAcmlKK2n6wQTRv1KUG3wctaALizAgrvcpqU/fP2hvHyIb/W5W2m8jiKuuMJ/L3/ru5dBJs/gHnLhWIdU4pKmGP3jILG+PoUFjKQYo86LE+e2lR6Exii57t5cJS35rok2tUjvPULpQvoa1xtCHUYD++HosHpZwNFpgCZRvoHBevANmffS4sEaz9WI6+a/gfg+cdKMnAGW4BPFbrd/Ar9hue5A3A1jTeGLn0UClb1e6MaeGvTXVXZ6dR8BOELYWLoOKkyin20lqcFGu0GCKNp/h5eJT3diYMXKFwtFreZpxB9py02PEy0Js85T5IrAztnbidNWXuKcNAVDdkA3Oz7k8KN1qefBnatbnHwdqcXwRjOs6R1Y/LTN7HfU0+5gZCb04pbq3/on+oa/R9gUVMy+mC1HVy6+b7Ft3vT1FxSWO5MRn22Hb2yhscL0vlPEmsEJDll6cmCTfY2M/Fr2iWMJDE9zfHG94IfcbceqmjHy+2QVe9ed0z7k6BL3AsT2OAk29Lzr1rPllk3iToa21HiYFcBs4BYzA8denlamnRhtwMWzDS/oqR0gukwxPqo6rVC+qFbwWj6+A="
    - secure: "iRjpo/vhoyjvKd2CRKIDyJNMEA8NaaKM4h3fJh0Si1XoSsbCb7YOhw93e3aGtBhhaunVBkOvLkbUIjLR8QCA+gLSX+db1VhSVX5trj8wHLMGmln5NSno9HylFU1dBAeEcCNhVY+dKkWEXxvZvZupA2hp3lJhmkbNWEqBJh7Z5GCWEe6KGqLTAzw10ZdVH05XgNE9VJPitH3mgqD0QP8934uF5uTBQe62dCGlHKSnNh2Abu64hpPiKXYmCgjBFeM/kI9G/rVa2CKLEyR4pHZKNC5Z2kuRdDM5WNiyNx5stMqPOwpqKJ77nakt+EhYnGvgcJeSWqGWoEYuYNg6LTuWztR2l8G1vY2CzmIvpQBp2cagrlUpPC7d17VkUP3zhXB7FIKdRzFpPUTaKdpSWBHeI+QwWqolc9f3SCOIINs69VfMUNdpxbGLnEpO8/nXMii5rPqcPpn7WH7cqBbDOmqz37nKny+uwtte2PAQIsCLdj58os1Mh+N+tZ+Kunz7T9ETnGF+emCMk8AKvrEDn67TrxUcSuBMcABgnizb9TV2Q61seeUQsopH2FwCetn5LVmvZBT+/bOipTa9M3i7CcDSkXnTV0YJxCipo3B75ff4KVpvqS8XZY/j1+THsh8H2QO1kkVDHRTYKgoeG9JxWbHfhlR2RwlcKthvLmV1Drn16kg="
